ESOUI_HOME = "https://www.esoui.com/downloads"
# Working download link is DOWNLOADS_TEMPLATE.replace('<id>, esoui_id)
DOWNLOADS_TEMPLATE = "https://www.esoui.com/downloads/file<id>/"
ADDON_INFO_TEMPLATE = "https://www.esoui.com/downloads/info<id>"
ADDON_PAGE_TEMPLATE = "https://www.esoui.com/downloads/index.php?cid=<cat>&sb=dec_date&so=desc&pt=f&page=<page>"
DB_NAME = "database\\rejuvenate.db"
INITIAL_MSG = "Welcome\nSetting things up now\nPlease be patient!"
NO_PATH_MSG = "We were unable to automatically find \nyour Addon folder. Please specify where \nyour Addon folder is located."
DB_UPDATE_MSG = "We are now setting up your\n database. This will take a little time.\nPlease sit tight..."
DB_ERROR_MSG = "There was an issue creating \nthe database. Sorry :(\nI can not proceed. \nClosing the application."
LOCAL_FIND_MSG = "Adding your installed addons\nto the database.\nAlmost done..."
CHECK_ADDONS_MSG = "Please review the next screen\nto make sure the addons\ninstalled locally match the\nones listed on the website"
CHECK_UPDATE_MSG = "Checking for the latest versions\nof your installed addons\nPlease stand by..."